connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password:

development:
  <<: *connection
  database: workshops_development

test: &test
  <<: *connection
  database: workshops_test

production:
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV["DATABASE_HOST"] %>
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>